#define F_CPU 2000000UL
#define F_PWM 24000UL
#define PWM_PRESCALER 1
#define BAUD 115200
#define RED_LED 3
#define GREEN_LED 4
#define SET_GREEN_LED  PORTA.OUTCLR = 1<<GREEN_LED
#define CLEAR_GREEN_LED  PORTA.OUTSET = 1<<GREEN_LED
#define SET_RED_LED  PORTA.OUTCLR = 1<<RED_LED
#define CLEAR_RED_LED  PORTA.OUTSET = 1<<RED_LED
#define PWM_PERIOD_REGISTER_VALUE F_CPU/(F_PWM*PWM_PRESCALER)-1

#define RPM_MEASUREMENT_COUNTER_RELOAD_VALUE 0xFFFF

#define MAX_N_PARAMS 5
#define MAX_COMMANDLENGTH 20
#define MAX_PARAMLENGTH 20

//Error/Warning codes
#define MORE_THAN_100_PERCENT_DUTY_CYCLE_REQUESTED 1
#define WARNING_RIGHT_MOTOR_NOT_CONFIGURED 2

