#define F_CPU 2000000UL
#define BAUD 115200
#define RED_LED 0
#define GREEN_LED 1
#define SET_GREEN_LED  PORTB.OUTSET = 1<<GREEN_LED
#define CLEAR_GREEN_LED  PORTB.OUTCLR = 1<<GREEN_LED
#define SET_RED_LED  PORTB.OUTSET = 1<<RED_LED
#define CLEAR_RED_LED  PORTB.OUTCLR = 1<<RED_LED

#define F_PWM 12000UL
#define PWM_PRESCALER 1
#define PWM_PERIOD_REGISTER_VALUE F_CPU/(F_PWM*PWM_PRESCALER)-1
